language: ruby
rvm:
- 2.2.0
- 2.1.3
- 2.0.0
- 1.9.3
- 1.9.2
- 1.8.7
- rbx
- ree
install:
- gem install bundler
- gem uninstall rake
- gem install rake
- bundle install
script:
- uname -s
- rake test
addons:
  code_climate:
    repo_token:
      secure: Na2Ghl3W0IpUWAWx66V9skLie5MqiJWfn7muCSRkAYIVL/j9fR6jhhawOKlX0R6bg4byouOyLieDu9HWsv2EY5L7JweVspodRuuaJndxDQ1E5rOp0mU6vDl7kIqBeboX3AsivXDgcc8C8qvE+WD++vr3oEMg22c2/RIbt6ecJGs=
